name: Codeigniter Workflow
on: push

jobs:
  build:
    name: Codeigniter build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/build-app
      #- run: ./vendor/bin/phpunit
      #- run: ./vendor/bin/phpcs